name: CI/CD Pipeline
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint code
        run: pip install flake8 && flake8 model.py
      - name: Run tests
        run: python model.py
  deploy:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - name: Deploy model
        run: echo "Deploying model..."
